<?php

/**
 * Hooks into ProcessDiagnostics to add additional PHP related information.
 */
class DiagnosePhp extends Wire implements Module
{

    public static function getModuleInfo()
    {
        return array(
            'title'     => __('PHP Diagnostics', __FILE__),
            'summary'   => __('Allows collection of PHP diagnostics', __FILE__),
            'version'   => 5,
            'permanent' => false,
            'autoload'  => false,
            'singular'  => true,
            'requires'  => 'ProcessDiagnostics',
            'installs'  => 'ProcessDiagnostics',
            'author'    => 'Stephen Dickinson, QBox',
        );
    }


    public function init()
    {
        $this->addHookAfter('ProcessDiagnostics::collectDiagnostics', $this, 'AppendDiagnostics');
    }

    /**
     * Collects Diagnostics.
     */
    public function GetDiagnostics()
    {
        $fail_limit = '5.3.8';

        $status = ProcessDiagnostics::$ok;
        $action = '';
        if (version_compare(PHP_VERSION, $fail_limit) < 0) {
            $status = ProcessDiagnostics::$fail;
            $action = $this->_("Upgrade your PHP installation to at least version ").$fail_limit;
        }

        $results[] = array(
            'title'  => $this->_('Version'),
            'value'  => PHP_VERSION,
            'status' => $status,
            'action' => $action,
        );

        $mem = trim(ini_get('memory_limit'));
        $results[] = array(
            'title'  => $this->_('Max Memory'),
            'value'  => $mem,
            'status' => ProcessDiagnostics::$ok,
            'action' => ''
        );


        $post_max_size = trim(ini_get('post_max_size'));
        $results[] = array(
            'title'  => $this->_('Post Max Size'),
            'value'  => $post_max_size,
            'status' => ProcessDiagnostics::$ok,
            'action' => '',
        );

        $upload_max_filesize = trim(ini_get('upload_max_filesize'));
        $results[] = array(
            'title'  => $this->_('Upload Max Filesize'),
            'value'  => $upload_max_filesize,
            'status' => ProcessDiagnostics::$ok,
            'action' => '',
        );

        $max_execution_time = trim(ini_get('max_execution_time'));
        $can_change = set_time_limit($max_execution_time);
        $can_change = ($can_change) ? $this->_("This can be extended by calling set_time_limit().") : $this->_("Fixed. Calling set_time_limit() has no effect.");
        $results[] = array(
            'title'  => $this->_('Maximum execution time'),
            'value'  => $max_execution_time,
            'status' => ProcessDiagnostics::$ok,
            'action' => $can_change,
        );

        $max_input_time = trim(ini_get('max_input_time'));
        $results[] = array(
            'title'  => $this->_('Maximum input time'),
            'value'  => $max_input_time,
            'status' => ProcessDiagnostics::$ok,
            'action' => '',
        );
        $api     = null;   // string  full api info
        $sys     = null;   // string  full sys info

        ob_start();
        phpinfo(INFO_GENERAL);
        $buffer = str_replace("\r\n", "\n", ob_get_contents());
        ob_end_clean();

        $ver = phpversion();

        $mem = trim(ini_get('memory_limit'));

        $pattern = preg_match('#</td>#msi', $buffer)===1 ? '#>Server API.*?</td><td.*?>(.*?)</td>#msi' : '#\nServer API.*?=>(.*?)\n#msi';
        $api = preg_match($pattern, $buffer, $matches)===1 ? trim($matches[1]) : null;

        $pattern = preg_match('#</td>#msi', $buffer)===1 ? '#>System.*?</td><td.*?>(.*?)</td>#msi' : '#\nSystem.*?=>(.*?)\n#msi';
        $sys = preg_match($pattern, $buffer, $matches)===1 ? trim($matches[1]) : null;


        // build results array PHP Handler
        $results[] = array(
            'title'  => $this->_('Handler'),
            'value'  => $api,
            'status' => ProcessDiagnostics::$ok,
            'action' => '',
        );


        // build results array PHP system info
        $results[] = array(
            'title'  => $this->_('System Information'),
            'value'  => $sys,
            'status' => ProcessDiagnostics::$ok,
            'action' => '',
        );

        $results[] = array(
            'title'  => $this->_('Timezone'),
            'value'  => $this->wire->config->timezone,
            'status' => ProcessDiagnostics::$ok,
            'action' => '',
        );

        return $results;
    }


    public function AppendDiagnostics($event)
    {
        $results = $event->return;
        $results[$this->_('PHP Diagnostics')] = $this->GetDiagnostics();
        $event->return = $results;
    }
}
